[build]
builder = "nixpacks"
watchPaths = ["server"]
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18.17.0"


