[build]
builder = "nixpacks"
watchPaths = ["server"]
buildCommand = "cd server && npm install && npm run build"

[deploy]
startCommand = "cd server && npm run prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18.17.0"
